export const BUSINESS_KEYS = [
  'business_name',
  'business_subtitle',
  'business_rif',
  'business_phone',
  'business_address',
  'business_city',
  'business_logo_url',
  'ticket_footer',
  'ticket_show_bs',
  'ticket_show_description',
  'ticket_show_ref',
  'ticket_show_address',
  'ticket_show_phone',
  'ticket_show_client',
  'ticket_show_rif',
  'ticket_show_cashier',
  'ticket_show_rate',
  'ticket_show_payment',
  'ticket_currency_symbol',
  'ticket_prefix',
  'ticket_width_mm',
  'event_name',
  'event_venue',
] as const

export type BusinessKey = (typeof BUSINESS_KEYS)[number]

export const BUSINESS_DEFAULTS: Record<BusinessKey, string> = {
  business_name:          'Sport Bar',
  business_subtitle:      'Guaiqueríes de Margarita',
  business_rif:           '',
  business_phone:         '',
  business_address:       '',
  business_city:          'Margarita, Venezuela',
  business_logo_url:      '',
  ticket_footer:          'Gracias por su visita',
  ticket_show_bs:         'true',
  ticket_show_description: 'false',
  ticket_show_ref:        'true',
  ticket_show_address:    'false',
  ticket_show_phone:      'false',
  ticket_show_client:     'true',
  ticket_show_rif:        'false',
  ticket_show_cashier:    'true',
  ticket_show_rate:       'false',
  ticket_show_payment:    'true',
  ticket_currency_symbol: 'REF',
  ticket_prefix:          'LOC',
  ticket_width_mm:        '58',
  event_name:             '',
  event_venue:            '',
}
